name: Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    
    - name: install
      run: yarn install
    
    - name: check style
      run: yarn run check:style

    - name: check typescript
      run: yarn run check:ts
